package com.dk.cp.quiz.dao;

import com.dk.cp.quiz.model.ChoiceOption;
import com.dk.cp.quiz.model.ChoiceOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChoiceOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_option
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    long countByExample(ChoiceOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_option
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int deleteByExample(ChoiceOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_option
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_option
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int insert(ChoiceOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_option
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int insertSelective(ChoiceOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_option
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    List<ChoiceOption> selectByExample(ChoiceOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_option
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    ChoiceOption selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_option
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") ChoiceOption record, @Param("example") ChoiceOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_option
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int updateByExample(@Param("record") ChoiceOption record, @Param("example") ChoiceOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_option
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int updateByPrimaryKeySelective(ChoiceOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_option
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int updateByPrimaryKey(ChoiceOption record);
}