package com.dk.cp.quiz.dao;

import com.dk.cp.quiz.model.ChoiceDraft;
import com.dk.cp.quiz.model.ChoiceDraftExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ChoiceDraftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_draft
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    long countByExample(ChoiceDraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_draft
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int deleteByExample(ChoiceDraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_draft
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_draft
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int insert(ChoiceDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_draft
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int insertSelective(ChoiceDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_draft
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    List<ChoiceDraft> selectByExample(ChoiceDraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_draft
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    ChoiceDraft selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_draft
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") ChoiceDraft record, @Param("example") ChoiceDraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_draft
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int updateByExample(@Param("record") ChoiceDraft record, @Param("example") ChoiceDraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_draft
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int updateByPrimaryKeySelective(ChoiceDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_choice_draft
     *
     * @mbg.generated Sat Dec 17 23:32:11 CST 2016
     */
    int updateByPrimaryKey(ChoiceDraft record);
}