package com.dk.cp.quiz.model;

public class ChoiceOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_choice_option.cid
     *
     * @mbg.generated Sat Dec 17 23:30:42 CST 2016
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_choice_option.option
     *
     * @mbg.generated Sat Dec 17 23:30:42 CST 2016
     */
    private String option;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_choice_option.checked
     *
     * @mbg.generated Sat Dec 17 23:30:42 CST 2016
     */
    private Boolean checked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_choice_option.cid
     *
     * @return the value of quiz_choice_option.cid
     *
     * @mbg.generated Sat Dec 17 23:30:42 CST 2016
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_choice_option.cid
     *
     * @param cid the value for quiz_choice_option.cid
     *
     * @mbg.generated Sat Dec 17 23:30:42 CST 2016
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_choice_option.option
     *
     * @return the value of quiz_choice_option.option
     *
     * @mbg.generated Sat Dec 17 23:30:42 CST 2016
     */
    public String getOption() {
        return option;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_choice_option.option
     *
     * @param option the value for quiz_choice_option.option
     *
     * @mbg.generated Sat Dec 17 23:30:42 CST 2016
     */
    public void setOption(String option) {
        this.option = option == null ? null : option.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_choice_option.checked
     *
     * @return the value of quiz_choice_option.checked
     *
     * @mbg.generated Sat Dec 17 23:30:42 CST 2016
     */
    public Boolean getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_choice_option.checked
     *
     * @param checked the value for quiz_choice_option.checked
     *
     * @mbg.generated Sat Dec 17 23:30:42 CST 2016
     */
    public void setChecked(Boolean checked) {
        this.checked = checked;
    }
}